/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-01-06 08:47:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/stylesheets/style.css\">\n");
      out.write("<link rel=\"icon\" href=\"/stylesheets/tbp.ico\" />\n");
      out.write("<title>TBP board</title>\n");
      out.write("<script type=\"text/javascript\"> \n");
      out.write("\t\n");
      out.write("\tfunction del() {\n");
      out.write("\t\tcommentList = document.querySelectorAll('.comment_view>ul');\n");
      out.write("\t\talert(\"댓글이 있는 글을 삭제할수 없습니다!\");\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction initPage() {\n");
      out.write("\t\tcountComments();\n");
      out.write("\t\tregisterEvents();\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction countComments() {\n");
      out.write("\t\tcommentList = document.querySelectorAll('.comment_view>ul');\n");
      out.write("\t\tcommentcount = document.querySelectorAll('.comment>p');\n");
      out.write("\t\tfor(var i =0 ; i < commentList.length ; i++) {\n");
      out.write("\t\t\tvar currentNode = commentList[i];\n");
      out.write("\t\t\tvar nPListCount = currentNode.querySelectorAll('li').length;\n");
      out.write("\t\t\tcommentcount[i].innerHTML = \"<a href='javascript:void(0)'>댓글 : \" + nPListCount + \"</a>\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction registerEvents() {\n");
      out.write("\t\tcommenttog = document.querySelectorAll('.comment>p');\n");
      out.write("\t\tfor (var i=0 ; i < commenttog.length ; i++) {\n");
      out.write("\t\t\tcommenttog[i].addEventListener('click',toggleComments, false);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tboardimg = document.querySelectorAll('.list_content>.image_s>img');\n");
      out.write("\t\tfor (var i=0 ; i < boardimg.length ; i++) {\n");
      out.write("\t\t\tboardimg[i].addEventListener('click',toggleimg, false);\n");
      out.write("\t\t\t//boardimg[i].addEventListener('mouseover',toggleimg, false);\n");
      out.write("\t\t\t//boardimg[i].addEventListener('mouseout',toggleimg, false);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tformList = document.querySelectorAll('.comment input[type=submit]');\n");
      out.write("\t\tfor ( var i=0 ; i < formList.length ; i++) {\n");
      out.write("\t\t\tformList[i].addEventListener('click',writeComments, false);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tcommentList = document.querySelectorAll('.comment_view>ul>li>button');\n");
      out.write("\t\tfor ( var i=0 ; i < commentList.length ; i++) {\n");
      out.write("\t\t\tcommentList[i].addEventListener('click',deleteComments, false);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tnewpost = document.querySelector('#list_new');\n");
      out.write("\t\tif(newpost) {\n");
      out.write("\t\t\tnewpost.addEventListener('click',togglenewpost, false);\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction togglenewpost(e) {\n");
      out.write("\t\twrapnewpost = document.querySelector('.wrap_new_post');\n");
      out.write("\t\tvar name =  wrapnewpost.className;\n");
      out.write("\t\tif (name === \"wrap_new_post hidden\") {\n");
      out.write("\t\t\twrapnewpost.className = \"wrap_new_post\";\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\twrapnewpost.className = \"wrap_new_post hidden\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\tfunction deleteComments(e) {\n");
      out.write("\t\tvar eleForm = e.toElement.parentElement.firstElementChild;\n");
      out.write("\t\tvar sID = eleForm.id;\n");
      out.write("\t\tvar url = \"/board/\" +sID + \"/comment_delete.json\";\n");
      out.write("\t\tvar request = new XMLHttpRequest();\n");
      out.write("\t\trequest.open(\"POST\" , url, true);\n");
      out.write("\t\trequest.onreadystatechange = function() {\n");
      out.write("\t\t\tif(request.readyState ==4 && request.status ==200) {\n");
      out.write("\t\t\t\tvar deletedcomment = e.toElement.parentElement;\n");
      out.write("\t\t\t\tvar comments = deletedcomment.parentElement.parentElement;\n");
      out.write("\t\t\t\tdeletedcomment.outerHTML = \"\";\n");
      out.write("\t\t\t\tvar commentsli = comments.querySelectorAll('ul>li');\n");
      out.write("\t\t\t\tcomments.style.height = commentsli.length * 19 + \"px\";\n");
      out.write("\t\t\t\tcountComments();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\trequest.send(sID);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction writeComments(e) {\n");
      out.write("\t\te.preventDefault();\n");
      out.write("\t\tvar eleForm = e.currentTarget.form;\n");
      out.write("\t\tvar textbox = eleForm.querySelectorAll('input[type=text]');\n");
      out.write("\t\tvar oFormData = new FormData(eleForm); //form data들을 자동으로 묶어준다.\n");
      out.write("\t\ttextbox[0].value = \"\";\n");
      out.write("\t\tvar sID = eleForm[0].value;\n");
      out.write("\t\tvar url = \"/board/\" +sID + \"/comments.json\";\n");
      out.write("\t\tvar request = new XMLHttpRequest();\n");
      out.write("\t\trequest.open(\"POST\" , url, true);\n");
      out.write("\t\trequest.onreadystatechange = function() {\n");
      out.write("\t\t\tif(request.readyState ==4 && request.status ==200) {\n");
      out.write("\t\t\t\tvar obj = JSON.parse(request.responseText);\n");
      out.write("\t\t\t\tvar eleCommentList = eleForm.parentNode.previousElementSibling;\n");
      out.write("\t\t\t\tvar eleCommentListul = eleCommentList.querySelectorAll('ul');\n");
      out.write("\t\t\t\tvar str_del = \"<button type=\\\"button\\\" name=\\\"c_delete\\\" onclick=\\'javascript:void(0)\\' id=\\\"\"+obj.id+\"\\\">x</button>\"\n");
      out.write("\t\t\t\teleCommentListul[0].insertAdjacentHTML(\"beforeend\" , \"<li>\"+obj.content+str_del+\"</li>\" );\n");
      out.write("\t\t\t\tvar eleCommentListli = eleCommentList.querySelectorAll('ul>li');\n");
      out.write("\t\t\t\teleCommentList.style.height = eleCommentListli.length * 19 + \"px\";\n");
      out.write("\t\t\t\teleCommentList.style.opacity = \"1\";\n");
      out.write("\t\t\t\tcountComments();\n");
      out.write("\t\t\t\tregisterEvents();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\trequest.send(oFormData);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction toggleComments(e) {\n");
      out.write("\t\tcomment = e.target.parentNode.parentNode.parentNode.getElementsByClassName('comment_view');\n");
      out.write("\t\tli = comment[0].querySelectorAll(\"ul>li\");\n");
      out.write("\t\tli_count = li.length;\n");
      out.write("\t\topacity = getStyle(comment[0], 'opacity');\n");
      out.write("\t\t\n");
      out.write("\t\tif(opacity === \"1\") {\n");
      out.write("\t\t\tcomment[0].style.opacity = \"0\";\n");
      out.write("\t\t\tcomment[0].style.height = \"0px\";\n");
      out.write("\t\t} else if(opacity === \"0\") {\n");
      out.write("\t\t\tcomment[0].style.opacity = \"1\";\n");
      out.write("\t\t\tcomment[0].style.height = li_count*19 + \"px\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction toggleimg(e) {\n");
      out.write("\t\tboard = e.target.parentElement.parentElement;\n");
      out.write("\t\thead = board.querySelectorAll('h1');\n");
      out.write("\t\tcontent_content = board.querySelectorAll('#content_content');\n");
      out.write("\t\tbuttons = board.querySelectorAll('.buttons');\n");
      out.write("\t\tcomment = board.querySelectorAll('.comment');\n");
      out.write("\t\tcomment_view = board.querySelectorAll('.comment_view');\n");
      out.write("\t\tstyle = window.getComputedStyle(head[0]);\n");
      out.write("\t\tdisplay = style.getPropertyValue('display');\n");
      out.write("\t\tif(display === \"none\") {\n");
      out.write("\t\t\thead[0].style.display = \"block\";\n");
      out.write("\t\t\tcontent_content[0].style.display = \"block\";\n");
      out.write("\t\t\tbuttons[0].style.display = \"block\";\n");
      out.write("\t\t\tcomment[0].style.display = \"block\";\n");
      out.write("\t\t} else if(display === \"block\") {\n");
      out.write("\t\t\thead[0].style.display = \"none\";\n");
      out.write("\t\t\tcontent_content[0].style.display = \"none\";\n");
      out.write("\t\t\tbuttons[0].style.display = \"none\";\n");
      out.write("\t\t\tcomment[0].style.display = \"none\";\n");
      out.write("\t\t\tcomment_view[0].style.opacity = \"0\";\n");
      out.write("\t\t\tcomment_view[0].style.height = \"0px\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction getStyle(element, propoerty) {\n");
      out.write("\t\tstyle = window.getComputedStyle(element);\n");
      out.write("\t\tresult = style.getPropertyValue(propoerty);\n");
      out.write("\t\treturn result;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\twindow.onload = initPage;\n");
      out.write("\t\n");
      out.write("/* \tfunction logincheck() {\n");
      out.write("\t\tvar userid = document.getElementById('userid');\n");
      out.write("\t\t//button[name=c_delete]\n");
      out.write("\t\tif(!userid) {\n");
      out.write("\t\t\talert(\"ID\");\n");
      out.write("\t\t}\n");
      out.write("\t\tconsole.log(userid.value);\n");
      out.write("\t} */\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"wrap\">\n");
      out.write("\t\t<header>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /list.jsp(179,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.userid}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t<h1>Welcome!</h1>\n");
        out.write("\t\t\t\t\t<div id=\"login\">\n");
        out.write("\t\t\t\t\t\t<form action=\"/login/get\" name=\"login\" method=\"POST\" enctype=\"multipart/form-data\">\n");
        out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"userid\" name=\"userid\" size=\"50\" placeholder=\"USER ID\"><br> \n");
        out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"password\" name=\"password\" size=\"50\" placeholder=\"PASSWORD\"><br>\n");
        out.write("\t\t\t\t\t\t\t<div class=buttons>\n");
        out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Login\">\n");
        out.write("\t\t\t\t\t\t\t\t<button type=\"button\" name=\"signin\" onclick=\"location.href='/login/form'\">Sign in</button>\n");
        out.write("\t\t\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t\t\t</form>\n");
        out.write("\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t<p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" 님 환영합니다.\n");
        out.write("\t\t\t\t\t\t<button type=\"button\" name=\"signout\" onclick=\"location.href='/logout'\">Logout</button>\n");
        out.write("\t\t\t\t\t</p>\n");
        out.write("\t\t</header>\n");
        out.write("\t\t<h1>Talk by Picture</h1>\n");
        out.write("\t\t<div id=\"board_list\">\n");
        out.write("\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t</div>\n");
        out.write("<!-- \t\t<div id=\"list_new\">\n");
        out.write("\t\t\t<button type=\"button\" name=\"new\"\n");
        out.write("\t\t\t\tonclick=\"location.href='/board/form'\">새글</button>\n");
        out.write("\t\t</div> -->\n");
        out.write("\t\t<!-- <div id=\"list_new\" onclick=\"location.href='/board/form'\">New Post</div> -->\n");
        out.write("\t\t<div id=\"list_new\">New Post</div>\n");
        out.write("\t\t\n");
        out.write("\t\t<div class=\"wrap_new_post hidden\">\n");
        out.write("\t\t\t<header>\n");
        out.write("\t\t\t\t<h1>New Post</h1>\n");
        out.write("\t\t\t</header>\n");
        out.write("\t\t\t<div id=\"new_post\">\n");
        out.write("\t\t\t \t<form action=\"/board\" method=\"POST\" enctype=\"multipart/form-data\">\n");
        out.write("\t\t\t \t<input type=\"text\" id=\"title\" name=\"title\" size=\"45\" placeholder=\"제목을 입력하세요\"><br>\n");
        out.write("\t\t\t \t<textarea id=\"contents\" name=\"contents\" rows=\"10\" cols=\"40\" placeholder=\"내용을 입력하세요\"></textarea><br>\n");
        out.write("\t\t\t \t<input type=\"file\" name=\"img_file\" size =\"20\" accept=\"image/*\" value=\"파일\"><br>\n");
        out.write("\t\t\t \t<input type=\"submit\" value=\"제출\">\n");
        out.write("\t\t\t \t<button type=\"button\" name=\"cancel\" onclick=\"location.href='/board/list'\">취소</button>\n");
        out.write("\t\t\t \t</form>\n");
        out.write("\t\t\t</div>\n");
        out.write("\t\t</div>\n");
        out.write("\t\t\n");
        out.write("\t\t<div class=\"wrap_modify_post hidden\">\n");
        out.write("\t\t\t\t<h1>Modify</h1>\n");
        out.write("\t\t\t<div id=\"modify_post\">\n");
        out.write("\t\t\t \t<form action=\"/board/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/modified\" method=\"POST\" enctype=\"multipart/form-data\">\n");
        out.write("\t\t\t \t<input type=\"text\" id=\"title\" name=\"title\" size=\"45\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\"><br>\n");
        out.write("\t\t\t \t<textarea id=\"contents\" name=\"contents\" rows=\"10\" cols=\"40\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</textarea><br>\n");
        out.write("\t\t\t \t<input type=\"file\" name=\"img_file\" size =\"20\" accept=\"image/*\"><br>\n");
        out.write("\t\t\t \t<input type=\"submit\" value=\"제출\">\n");
        out.write("\t\t\t \t<button type=\"button\" name=\"cancel\" onclick=\"location.href='/board/list'\">취소</button>\n");
        out.write("\t\t\t \t</form>\n");
        out.write("\t\t\t</div>\n");
        out.write("\t\t</div>\n");
        out.write("\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
    // /list.jsp(199,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/list.jsp(199,3) '${boardlist}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${boardlist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /list.jsp(199,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("item");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t<div class=\"list_content\">\n");
          out.write("\t\t\t\t\t<h1>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</h1>\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t<div id=\"content_content\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</div>\n");
          out.write("\t\t\t\t\t<div class=buttons>\n");
          out.write("\t\t\t\t\t\t<button type=\"button\" name=\"modify\"\n");
          out.write("\t\t\t\t\t\t\tonclick=\"location.href='/board/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/modify'\">수정</button>\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t<div class=\"comment_view\">\n");
          out.write("\t\t\t\t\t\t<ul>\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t\t</ul>\n");
          out.write("\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t<div class=\"comment\">\n");
          out.write("\t\t\t\t\t\t<p></p>\n");
          out.write("\t\t\t\t\t\t<form action=\"/board/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/comment\" method=\"POST\" enctype=\"multipart/form-data\">\n");
          out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"id\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"> \n");
          out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"content\" name=\"content\" placeholder=\"댓글을 입력하세요\">\n");
          out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"댓글\"><br>\n");
          out.write("\t\t\t\t\t\t</form>\n");
          out.write("\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t</div>\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /list.jsp(202,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty item.attachment}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t\t<div class=image style=\"background-image:url('/images/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.attachment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("');\"></div>\n");
        out.write("\t\t\t\t\t\t<div class=image_s><img src=\"/images/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.attachment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\"></div>\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
    if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /list.jsp(211,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty item.comments}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t\t\t\t<button type=\"button\" name=\"delete\" onclick=\"del()\">삭제</button>\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t\t\t\t<button type=\"button\" name=\"delete\"\n");
        out.write("\t\t\t\t\t\t\t\t\tonclick=\"location.href='/board/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/delete'\">삭제</button>\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /list.jsp(222,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/list.jsp(222,7) '${item.comments}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${item.comments}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /list.jsp(222,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("comment");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t<li>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" name=\"c_delete\" onclick='javascript:void(0)' id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">x</button>\n");
          out.write("\t\t\t\t\t\t\t\t</li>\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
